name: route-master
version: '3.8'

services:
  app:
    build: .
    image: django-image
    container_name: dj-container
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - '${PORT}:8000'
    volumes:
      - ./src:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:bullseye
    container_name: pg-container
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
