line-length = 88

[lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behaviour by
# explicitly adding the rule
extend-select=["E501","N","R","I"]
ignore=["F401"]